name: Black & Isort

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analysing the code with black & isort
      run: |
        black --check --diff .
        isort --check-only .
    - name: Test with Pytest
      env:
        MONGODB_ATLAS_HOST: ${{ secrets.MONGODB_ATLAS_HOST }}
        MONGODB_ATLAS_USER: ${{ secrets.MONGODB_ATLAS_USER }}
        MONGODB_ATLAS_PASSWORD: ${{ secrets.MONGODB_ATLAS_PASSWORD }}
      run: |
        pytest -v -m smoke && pytest -v -m "not smoke"
